# Generated by Django 2.2 on 2021-04-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_list', '0003_auto_20210422_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='guest_photo',
            field=models.ImageField(blank=True, upload_to='guest_photo/'),
        ),
    ]
