# Generated by Django 2.2 on 2021-04-23 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_list', '0004_registration_guest_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='choices_input',
            field=models.CharField(blank=True, choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five')], max_length=1),
        ),
        migrations.AlterField(
            model_name='registration',
            name='guest_photo',
            field=models.FileField(blank=True, upload_to='guest_photo/'),
        ),
    ]
