# Generated by Django 2.2 on 2021-04-23 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_list', '0005_auto_20210423_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='multiple_choices_input',
            field=models.CharField(blank=True, choices=[('1', 'Take'), ('2', 'a break'), ('3', 'Make'), ('4', 'a coffe'), ('5', 'Napping')], max_length=2),
        ),
    ]
