# Generated by Django 2.2 on 2021-04-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_list', '0006_registration_multiple_choices_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='choices_input',
            field=models.CharField(blank=True, choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five')], max_length=255),
        ),
        migrations.AlterField(
            model_name='registration',
            name='multiple_choices_input',
            field=models.CharField(blank=True, choices=[('1', 'Take'), ('2', 'a break'), ('3', 'Make'), ('4', 'a coffe'), ('5', 'Napping')], max_length=255),
        ),
    ]
